name: OIDC Actions

on:
  workflow_dispatch:
  push:

env:
  region: "ap-northeast-1"

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ASSUMED_ROLE }}
          aws-region: ${{ env.region }}
